var hmiItemEnum={
    db40_8:{
        archive:true,
        dataType:'R4',
        comment:'主油箱油温',
    },
    db40_12:{
        archive:true,
        dataType:'R4',
        comment:'齿轮油油温',
    },
    db40_16:{
        archive:true,
        dataType:'R4',
        comment:'刀盘转速设定',
    },
    db40_20:{
        archive:true,
        dataType:'R4',
        comment:'刀盘转速',
    },
    db40_24:{
        archive:true,
        dataType:'R4',
        comment:'刀盘压力',
    },
    db40_32:{
        archive:true,
        dataType:'R4',
        comment:'推进压力',
    },
    db40_36:{
        archive:true,
        dataType:'R4',
        comment:'推进速度',
    },
    db40_40:{
        archive:true,
        dataType:'R4',
        comment:'推进压力A设定',
    },
    db40_44:{
        archive:true,
        dataType:'R4',
        comment:'A组推进压力',
    },
    db40_48:{
        archive:true,
        dataType:'R4',
        comment:'推进压力B设定',
    },
    db40_52:{
        archive:true,
        dataType:'R4',
        comment:'B组推进压力',
    },
    db40_56:{
        archive:true,
        dataType:'R4',
        comment:'推进压力C设定',
    },
    db40_60:{
        archive:true,
        dataType:'R4',
        comment:'C组推进压力',
    },
    db40_64:{
        archive:true,
        dataType:'R4',
        comment:'推进压力D设定',
    },
    db40_68:{
        archive:true,
        dataType:'R4',
        comment:'D组推进压力',
    },
    db40_72:{
        archive:true,
        dataType:'R4',
        comment:'设备桥压力',
    },
    db40_76:{
        archive:true,
        dataType:'R4',
        comment:'铰接压力',
    },
    db40_80:{
        archive:true,
        dataType:'R4',
        comment:'盾尾密封前部右上压力',
    },
    db40_84:{
        archive:true,
        dataType:'R4',
        comment:'盾尾密封前部正右压力',
    },
    db40_88:{
        archive:true,
        dataType:'R4',
        comment:'盾尾密封前部右上压力',
    },
    db40_92:{
        archive:true,
        dataType:'R4',
        comment:'盾尾密封前部左下压力',
    },
    db40_96:{
        archive:true,
        dataType:'R4',
        comment:'盾尾密封后部右上压力',
    },
    db40_100:{
        archive:true,
        dataType:'R4',
        comment:'盾尾密封后部正右压力',
    },
    db40_104:{
        archive:true,
        dataType:'R4',
        comment:'盾尾密封后部右下压力',
    },
    db40_108:{
        archive:true,
        dataType:'R4',
        comment:'盾尾密封后部左下压力',
    },
    db40_112:{
        archive:true,
        dataType:'R4',
        comment:'螺机转速设定',
    },
    db40_116:{
        archive:true,
        dataType:'R4',
        comment:'螺机转速',
    },
    db40_120:{
        archive:true,
        dataType:'R4',
        comment:'螺机泵压力',
    },
    db40_124:{
        archive:true,
        dataType:'R4',
        comment:'滚动角',
    },
    db40_128:{
        archive:true,
        dataType:'R4',
        comment:'螺机后部压力',
    },
    db40_136:{
        archive:true,
        dataType:'R4',
        comment:'膨润土流量设定',
    },
    db40_140:{
        archive:true,
        dataType:'R4',
        comment:'左中土仓压力',
    },
    db40_144:{
        archive:true,
        dataType:'R4',
        comment:'左上土仓压力',
    },
    db40_148:{
        archive:true,
        dataType:'R4',
        comment:'左下土仓压力',
    },
    db40_152:{
        archive:true,
        dataType:'R4',
        comment:'右下土仓压力',
    },
    db40_156:{
        archive:true,
        dataType:'R4',
        comment:'右中土仓压力',
    },
    db40_360:{
        archive:true,
        dataType:'R4',
        comment:'顶部土仓压力',
    },
    db40_160:{
        archive:true,
        dataType:'R4',
        comment:'膨润土压力',
    },
    db40_164:{
        archive:true,
        dataType:'R4',
        comment:'螺机油温',
    },
    db40_168:{
        archive:true,
        dataType:'R4',
        comment:'左上注浆压力',
    },
    db40_172:{
        archive:true,
        dataType:'R4',
        comment:'右上注浆压力',
    },
    db40_176:{
        archive:true,
        dataType:'R4',
        comment:'右下注浆压力',
    },
    db40_180:{
        archive:true,
        dataType:'R4',
        comment:'左下注浆压力',
    },
    db40_184:{
        archive:true,
        dataType:'R4',
        comment:'盾尾密封前部正左压力',
    },
    db40_240:{
        archive:true,
        dataType:'R4',
        comment:'盾尾密封前部左上压力',
    },
    db40_244:{
        archive:true,
        dataType:'R4',
        comment:'盾尾密封后部正左压力',
    },
    db40_248:{
        archive:true,
        dataType:'R4',
        comment:'盾尾密封后部左上压力',
    },
    db40_252:{
        archive:true,
        dataType:'R4',
        comment:'刀盘补油压力',
    },
    db40_256:{
        archive:true,
        dataType:'R4',
        comment:'盾壳膨润土压力',
    },
    db40_260:{
        archive:true,
        dataType:'R4',
        comment:'螺机前部压力',
    },
    db40_276:{
        archive:true,
        dataType:'R4',
        comment:'盾壳膨润土流量',
    },
    db40_316:{
        archive:true,
        dataType:'R4',
        comment:'盾壳膨润土流量设定',
    },
    db40_320:{
        archive:true,
        dataType:'R4',
        comment:'推进速度',
    },
    db40_336:{
        archive:true,
        dataType:'R4',
        comment:'刀盘扭矩',
    },
    db40_340:{
        archive:true,
        dataType:'R4',
        comment:'螺机扭矩',
    },
    db40_344:{
        archive:true,
        dataType:'R4',
        comment:'皮带机转速',
    },
    db40_512:{
        archive:true,
        dataType:'R4',
        comment:'A组推进位移',
    },
    db40_516:{
        archive:true,
        dataType:'R4',
        comment:'B组推进位移',
    },
    db40_520:{
        archive:true,
        dataType:'R4',
        comment:'C组推进位移',
    },
    db40_524:{
        archive:true,
        dataType:'R4',
        comment:'D组推进位移',
    },
    db40_528:{
        archive:true,
        dataType:'R4',
        comment:'右上铰接位移',
    },
    db40_532:{
        archive:true,
        dataType:'R4',
        comment:'右下铰接位移',
    },
    db40_536:{
        archive:true,
        dataType:'R4',
        comment:'左下铰接位移',
    },
    db40_540:{
        archive:true,
        dataType:'R4',
        comment:'左上铰接位移',
    },
    db40_552:{
        archive:true,
        dataType:'R4',
        comment:'总推进力',
    },
    db40_886:{
        archive:true,
        dataType:'R4',
        comment:'俯仰角',
    },
    db40_1232:{
        archive:true,
        dataType:'R4',
        comment:'贯入度',
    },
    db40_756:{
        archive:true,
        dataType:'R4',
        comment:'总功率',
    },
    db40_760:{
        archive:true,
        dataType:'R4',
        comment:'总视在功率',
    },
    db40_764:{
        archive:true,
        dataType:'R4',
        comment:'总无功功率',
    },
    db40_768:{
        archive:true,
        dataType:'R4',
        comment:'功率因数',
    },
    db40_772:{
        archive:true,
        dataType:'R4',
        comment:'频率',
    },
    db40_776:{
        archive:true,
        dataType:'R4',
        comment:'平均相电压',
    },
    db40_780:{
        archive:true,
        dataType:'R4',
        comment:'平均线电压',
    },
    db40_784:{
        archive:true,
        dataType:'R4',
        comment:'平均电流',
    },
    db40_788:{
        archive:true,
        dataType:'R4',
        comment:'工作时间',
    },
    db40_792:{
        archive:true,
        dataType:'R4',
        comment:'L1相电压',
    },
    db40_796:{
        archive:true,
        dataType:'R4',
        comment:'L2相电压',
    },
    db40_800:{
        archive:true,
        dataType:'R4',
        comment:'L3相电压',
    },
    db40_804:{
        archive:true,
        dataType:'R4',
        comment:'L1线电压',
    },
    db40_808:{
        archive:true,
        dataType:'R4',
        comment:'L2线电压',
    },
    db40_812:{
        archive:true,
        dataType:'R4',
        comment:'L3线电压',
    },
    db40_816:{
        archive:true,
        dataType:'R4',
        comment:'L1相电流',
    },
    db40_820:{
        archive:true,
        dataType:'R4',
        comment:'L2相电流',
    },
    db40_824:{
        archive:true,
        dataType:'R4',
        comment:'L3相电流',
    },
    db40_828:{
        archive:true,
        dataType:'R4',
        comment:'L1相功率',
    },
    db40_832:{
        archive:true,
        dataType:'R4',
        comment:'L2相功率',
    },
    db40_836:{
        archive:true,
        dataType:'R4',
        comment:'L3相功率',
    },
    db40_840:{
        archive:true,
        dataType:'R4',
        comment:'L1相功率因数',
    },
    db40_844:{
        archive:true,
        dataType:'R4',
        comment:'L2相功率因数',
    },
    db40_848:{
        archive:true,
        dataType:'R4',
        comment:'L3相功率因数',
    },
    db40_852:{
        archive:true,
        dataType:'R4',
        comment:'L1相电压谐波',
    },
    db40_856:{
        archive:true,
        dataType:'R4',
        comment:'L2相电压谐波',
    },
    db40_860:{
        archive:true,
        dataType:'R4',
        comment:'L3相电压谐波',
    },
    db40_864:{
        archive:true,
        dataType:'R4',
        comment:'L1相电流谐波',
    },
    db40_868:{
        archive:true,
        dataType:'R4',
        comment:'L2相电流谐波',
    },
    db40_872:{
        archive:true,
        dataType:'R4',
        comment:'L3相电流谐波',
    },
    db40_1202:{
        archive:true,
        dataType:'R4',
        comment:'刀盘磨损压力',
    },
    db40_1286:{
        archive:true,
        dataType:'R4',
        comment:'拼装机抓举头压力',
    },
    db40_1372:{
        archive:true,
        dataType:'R4',
        comment:'刀盘控制油压检测',
    },
    db40_1376:{
        archive:true,
        dataType:'R4',
        comment:'螺机控制油压检测',
    },
    db40_1380:{
        archive:true,
        dataType:'R4',
        comment:'铰接泵出口压力检测',
    },
    db40_1400:{
        archive:true,
        dataType:'R4',
        comment:'转速控制油压',
    },
    db49_80:{
        archive:true,
        dataType:'R4',
        comment:'泡沫原液当前环累计量',
    },
    db49_84:{
        archive:true,
        dataType:'R4',
        comment:'泡沫原液总累计量',
    },
    db49_88:{
        archive:true,
        dataType:'R4',
        comment:'工业水当前环累计量',
    },
    db49_92:{
        archive:true,
        dataType:'R4',
        comment:'工业水总累计量',
    },
    db49_96:{
        archive:true,
        dataType:'R4',
        comment:'泡沫混合液当前环累计量',
    },
    db49_100:{
        archive:true,
        dataType:'R4',
        comment:'泡沫混合液总累计量',
    },
    db49_116:{
        archive:true,
        dataType:'R4',
        comment:'注浆A液当前环累计量',
    },
    db49_120:{
        archive:true,
        dataType:'R4',
        comment:'注浆A液总累计量',
    },
    db49_124:{
        archive:true,
        dataType:'R4',
        comment:'注浆右上A液当前环累计量',
    },
    db49_128:{
        archive:true,
        dataType:'R4',
        comment:'注浆右下A液当前环累计量',
    },
    db49_132:{
        archive:true,
        dataType:'R4',
        comment:'注浆左下A液当前环累计量',
    },
    db49_136:{
        archive:true,
        dataType:'R4',
        comment:'注浆左上A液当前环累计量',
    },
    db49_156:{
        archive:true,
        dataType:'R4',
        comment:'注浆B液当前环累计量',
    },
    db49_160:{
        archive:true,
        dataType:'R4',
        comment:'注浆B液总累计量',
    },
    db49_164:{
        archive:true,
        dataType:'R4',
        comment:'注浆右上B液当前环累计量',
    },
    db49_168:{
        archive:true,
        dataType:'R4',
        comment:'注浆右下B液当前环累计量',
    },
    db49_172:{
        archive:true,
        dataType:'R4',
        comment:'注浆左下B液当前环累计量',
    },
    db49_176:{
        archive:true,
        dataType:'R4',
        comment:'注浆左上B液当前环累计量',
    },
    db49_180:{
        archive:true,
        dataType:'R4',
        comment:'刀盘喷水当前环累计量',
    },
    db49_184:{
        archive:true,
        dataType:'R4',
        comment:'刀盘喷水总累计量',
    },
    db49_204:{
        archive:true,
        dataType:'R4',
        comment:'膨润土当前环累计量',
    },
    db49_208:{
        archive:true,
        dataType:'R4',
        comment:'膨润土总累计量',
    },
    db49_212:{
        archive:true,
        dataType:'R4',
        comment:'盾壳膨润土当前环累计量',
    },
    db49_216:{
        archive:true,
        dataType:'R4',
        comment:'盾壳膨润土总累计量',
    },
    db49_240:{
        archive:true,
        dataType:'R4',
        comment:'刀盘当前累计工作时间',
    },
    db49_244:{
        archive:true,
        dataType:'R4',
        comment:'刀盘总累计工作时间',
    },
    db49_280:{
        archive:true,
        dataType:'R4',
        comment:'HBW密封油脂当前环累计量',
    },
    db49_284:{
        archive:true,
        dataType:'R4',
        comment:'HBW密封油脂总累计量',
    },
    db49_288:{
        archive:true,
        dataType:'R4',
        comment:'EP2润滑油脂当前环累计量',
    },
    db49_292:{
        archive:true,
        dataType:'R4',
        comment:'EP2润滑油脂总累计量',
    },
    db49_296:{
        archive:true,
        dataType:'R4',
        comment:'盾尾密封当前环累计量',
    },
    db49_300:{
        archive:true,
        dataType:'R4',
        comment:'盾尾密封总累计量',
    },
    db49_328:{
        archive:true,
        dataType:'R4',
        comment:'电量环累计量',
    },
    db49_332:{
        archive:true,
        dataType:'R4',
        comment:'电量总累计量',
    },
    db47_60:{
        archive:true,
        dataType:'R4',
        comment:'VMT导向水平后',
    },
    db47_64:{
        archive:true,
        dataType:'R4',
        comment:'VMT导向垂直后',
    },
    db47_52:{
        archive:true,
        dataType:'R4',
        comment:'VMT导向水平前',
    },
    db47_56:{
        archive:true,
        dataType:'R4',
        comment:'VMT导向垂直前',
    },
    db47_76:{
        archive:true,
        dataType:'R4',
        comment:'VMT导向水平趋向RP',
    },
    db47_80:{
        archive:true,
        dataType:'R4',
        comment:'VMT导向垂直趋向RP',
    },
    db47_16:{
        archive:true,
        dataType:'R4',
        comment:'VMT导向里程',
    },
    db47_4:{
        archive:true,
        dataType:'R4',
        comment:'VMT导向滚动角',
    },
    db47_0:{
        archive:true,
        dataType:'R4',
        comment:'VMT导向仰附角',
    },
    db47_256:{
        archive:true,
        dataType:'R4',
        comment:'VMT导向掘进环数',
    },
    db46_36:{
        archive:true,
        dataType:'R4',
        comment:'VMT导向推进油缸位移A',
    },
    db46_40:{
        archive:true,
        dataType:'R4',
        comment:'VMT导向推进油缸位移B',
    },
    db46_44:{
        archive:true,
        dataType:'R4',
        comment:'VMT导向推进油缸位移C',
    },
    db46_48:{
        archive:true,
        dataType:'R4',
        comment:'VMT导向推进油缸位移D',
    },
    db40_28:{
        archive:false,
        dataType:'R4',
        comment:'刀盘油温',
    },
    db49_404:{
        archive:false,
        dataType:'U2',
        comment:'当前环号',
    },
    db40_880:{
        archive:false,
        dataType:'R4',
        comment:'超挖刀盘角度',
    },
    db40_884_0:{
        archive:false,
        dataType:'B4',
        comment:'主控室控制按钮指示灯',
    },
    db40_884_1:{
        archive:false,
        dataType:'B4',
        comment:'自动模式指示灯',
    },
    db40_884_2:{
        archive:false,
        dataType:'B4',
        comment:'左上注浆启动指示灯',
    },
    db40_884_3:{
        archive:false,
        dataType:'B4',
        comment:'左下注浆启动指示灯',
    },
    db40_884_4:{
        archive:false,
        dataType:'B4',
        comment:'右上注浆启动指示灯',
    },
    db40_884_5:{
        archive:false,
        dataType:'B4',
        comment:'右下注浆启动指示灯',
    },
    db40_884_6:{
        archive:false,
        dataType:'B4',
        comment:'搅拌机启动指示灯',
    },
    db40_884_7:{
        archive:false,
        dataType:'B4',
        comment:'搅拌停止指示灯',
    },
    db40_938_0:{
        archive:false,
        dataType:'B4',
        comment:'HBW与刀盘调试模式指示灯',
    },
    db40_938_2:{
        archive:false,
        dataType:'B4',
        comment:'自动模式启动指示灯',
    },
    db40_940:{
        archive:false,
        dataType:'R4',
        comment:'齿轮油密封压力',
    },
    db40_958:{
        archive:false,
        dataType:'R4',
        comment:'抓举头角度',
    },
    db40_974:{
        archive:false,
        dataType:'R4',
        comment:'铰接右下压力',
    },
    db40_978:{
        archive:false,
        dataType:'R4',
        comment:'铰接左下压力',
    },
    db40_982:{
        archive:false,
        dataType:'R4',
        comment:'铰接左上压力',
    },
    db40_986:{
        archive:false,
        dataType:'R4',
        comment:'铰接右上压力',
    },
    db40_990_0:{
        archive:false,
        dataType:'B4',
        comment:'铰接高压灯',
    },
    db40_990_1:{
        archive:false,
        dataType:'B4',
        comment:'铰接右上控制指示灯',
    },
    db40_990_2:{
        archive:false,
        dataType:'B4',
        comment:'铰接右下控制指示灯',
    },
    db40_990_3:{
        archive:false,
        dataType:'B4',
        comment:'铰接左下控制指示灯',
    },
    db40_990_4:{
        archive:false,
        dataType:'B4',
        comment:'铰接左上控制指示灯',
    },
    db40_991_0:{
        archive:false,
        dataType:'B4',
        comment:'膨润土气动球阀启动指示灯',
    },
    db40_991_1:{
        archive:false,
        dataType:'B4',
        comment:'膨润土3路启动指示灯',
    },
    db40_991_2:{
        archive:false,
        dataType:'B4',
        comment:'膨润土4路启动指示灯',
    },
    db40_991_3:{
        archive:false,
        dataType:'B4',
        comment:'膨润土5路启动指示灯',
    },
    db40_991_4:{
        archive:false,
        dataType:'B4',
        comment:'膨润土6路启动指示灯',
    },
    db40_992:{
        archive:false,
        dataType:'R4',
        comment:'螺机补油压力',
    },
    db40_1000:{
        archive:false,
        dataType:'R4',
        comment:'左上有杆腔压力',
    },
    db40_1004:{
        archive:false,
        dataType:'R4',
        comment:'左上无杆腔压力',
    },
    db40_1008:{
        archive:false,
        dataType:'R4',
        comment:'右上有杆腔压力',
    },
    db40_1012:{
        archive:false,
        dataType:'R4',
        comment:'右上无杆腔压力',
    },
    db40_1016:{
        archive:false,
        dataType:'R4',
        comment:'B液流量',
    },
    db40_1020:{
        archive:false,
        dataType:'R4',
        comment:'A液流量',
    },
    db40_1028:{
        archive:false,
        dataType:'R4',
        comment:'A液压力',
    },
    db40_1032:{
        archive:false,
        dataType:'R4',
        comment:'B液流量目标值',
    },
    db40_1036:{
        archive:false,
        dataType:'R4',
        comment:'B液压力',
    },
    db40_1040_0:{
        archive:false,
        dataType:'B4',
        comment:'单液注浆模式指示灯',
    },
    db40_1040_1:{
        archive:false,
        dataType:'B4',
        comment:'双液１路启动指示灯',
    },
    db40_1040_2:{
        archive:false,
        dataType:'B4',
        comment:'双液２路启动指示灯',
    },
    db40_1040_3:{
        archive:false,
        dataType:'B4',
        comment:'双液启动指示灯',
    },
    db40_1040_4:{
        archive:false,
        dataType:'B4',
        comment:'双液停止指示灯',
    },
    db40_1040_5:{
        archive:false,
        dataType:'B4',
        comment:'双液注浆模式指示灯',
    },
    db40_1040_6:{
        archive:false,
        dataType:'B4',
        comment:'双液注浆A液清洗指示灯',
    },
    db40_1046:{
        archive:false,
        dataType:'R4',
        comment:'砂浆体积',
    },
    db40_1054:{
        archive:false,
        dataType:'R4',
        comment:'四路泡沫流量实测值',
    },
    db40_1058:{
        archive:false,
        dataType:'R4',
        comment:'五路泡沫流量实测值',
    },
    db40_1062:{
        archive:false,
        dataType:'R4',
        comment:'六路泡沫流量实测值',
    },
    db40_1078:{
        archive:false,
        dataType:'R4',
        comment:'四路空气流量实测值',
    },
    db40_1102:{
        archive:false,
        dataType:'R4',
        comment:'四路压力',
    },
    db40_1126_0:{
        archive:false,
        dataType:'B4',
        comment:'四路激活指示灯',
    },
    db40_1126_6:{
        archive:false,
        dataType:'B4',
        comment:'四路泡沫启动指示灯',
    },
    db40_1152:{
        archive:false,
        dataType:'R4',
        comment:'四路空气流量设置值',
    },
    db40_1200_0:{
        archive:false,
        dataType:'B4',
        comment:'四路空气启动指示灯',
    },
    db40_1206:{
        archive:false,
        dataType:'R4',
        comment:'HBW内密封压力',
    },
    db40_1210:{
        archive:false,
        dataType:'R4',
        comment:'HBW外密封压力',
    },
    db40_1220:{
        archive:false,
        dataType:'R4',
        comment:'超挖量',
    },
    db40_1238:{
        archive:false,
        dataType:'R4',
        comment:'皮带机张紧压力',
    },
    db43_16:{
        archive:false,
        dataType:'R4',
        comment:'刀盘泄油预警值',
    },
    db43_20:{
        archive:false,
        dataType:'R4',
        comment:'刀盘泄油报警值',
    },
    db43_108:{
        archive:false,
        dataType:'R4',
        comment:'齿轮油密封最小压力',
    },
    db43_112:{
        archive:false,
        dataType:'R4',
        comment:'齿轮油密封最大压力',
    },
    db43_136:{
        archive:false,
        dataType:'R4',
        comment:'刀盘最大压力',
    },
    db43_483_1:{
        archive:false,
        dataType:'B4',
        comment:'HBW与刀盘调试模式按钮',
    },
    db43_483_4:{
        archive:false,
        dataType:'B4',
        comment:'管片安装机编码器复位按钮',
    },
    db43_490:{
        archive:false,
        dataType:'R4',
        comment:'左上速度设定值',
    },
    db43_506:{
        archive:false,
        dataType:'R4',
        comment:'管片顺转角度',
    },
    db43_510:{
        archive:false,
        dataType:'R4',
        comment:'管片逆转角度',
    },
    db43_514_0:{
        archive:false,
        dataType:'B4',
        comment:'铰接右上控制按钮',
    },
    db43_514_1:{
        archive:false,
        dataType:'B4',
        comment:'铰接右下控制按钮',
    },
    db43_514_2:{
        archive:false,
        dataType:'B4',
        comment:'铰接左下控制按钮',
    },
    db43_514_3:{
        archive:false,
        dataType:'B4',
        comment:'铰接左上控制按钮',
    },
    db43_515_0:{
        archive:false,
        dataType:'B4',
        comment:'膨润土气动球阀启动',
    },
    db43_515_1:{
        archive:false,
        dataType:'B4',
        comment:'膨润土3路启动',
    },
    db43_515_2:{
        archive:false,
        dataType:'B4',
        comment:'膨润土4路启动',
    },
    db43_515_3:{
        archive:false,
        dataType:'B4',
        comment:'膨润土5路启动',
    },
    db43_515_4:{
        archive:false,
        dataType:'B4',
        comment:'膨润土6路启动',
    },
    db43_516_0:{
        archive:false,
        dataType:'B4',
        comment:'单液注浆模式按钮',
    },
    db43_516_1:{
        archive:false,
        dataType:'B4',
        comment:'双液启动',
    },
    db43_516_2:{
        archive:false,
        dataType:'B4',
        comment:'双液停止',
    },
    db43_516_3:{
        archive:false,
        dataType:'B4',
        comment:'A液速度增加按钮',
    },
    db43_516_4:{
        archive:false,
        dataType:'B4',
        comment:'A液速度减小按钮',
    },
    db43_516_5:{
        archive:false,
        dataType:'B4',
        comment:'双液１路启动按钮',
    },
    db43_516_6:{
        archive:false,
        dataType:'B4',
        comment:'双液２路启动按钮',
    },
    db43_516_7:{
        archive:false,
        dataType:'B4',
        comment:'双液注浆模式按钮',
    },
    db43_517_0:{
        archive:false,
        dataType:'B4',
        comment:'左上速度设置增加按钮',
    },
    db43_517_1:{
        archive:false,
        dataType:'B4',
        comment:'左上速度设置减小按钮',
    },
    db43_517_2:{
        archive:false,
        dataType:'B4',
        comment:'左下速度设置增加按钮',
    },
    db43_517_3:{
        archive:false,
        dataType:'B4',
        comment:'左下速度设置减小按钮',
    },
    db43_517_4:{
        archive:false,
        dataType:'B4',
        comment:'右上速度设置增加按钮',
    },
    db43_517_5:{
        archive:false,
        dataType:'B4',
        comment:'右上速度设置减小按钮',
    },
    db43_517_6:{
        archive:false,
        dataType:'B4',
        comment:'右下速度设置增加按钮',
    },
    db43_517_7:{
        archive:false,
        dataType:'B4',
        comment:'右下速度设置减小按钮',
    },
    db43_518_0:{
        archive:false,
        dataType:'B4',
        comment:'四路激活按钮',
    },
    db43_518_6:{
        archive:false,
        dataType:'B4',
        comment:'四路泡沫启动按钮',
    },
    db43_520:{
        archive:false,
        dataType:'R4',
        comment:'四路膨胀率',
    },
    db43_544:{
        archive:false,
        dataType:'R4',
        comment:'四路泡沫流量',
    },
    db43_568_0:{
        archive:false,
        dataType:'B4',
        comment:'四路空气启动按钮',
    },
    db43_568_6:{
        archive:false,
        dataType:'B4',
        comment:'四路泡沫增加按钮',
    },
    db43_568_7:{
        archive:false,
        dataType:'B4',
        comment:'四路泡沫减小按钮',
    },
    db43_569_0:{
        archive:false,
        dataType:'B4',
        comment:'四路空气增加按钮',
    },
    db43_569_1:{
        archive:false,
        dataType:'B4',
        comment:'四路空气减小按钮',
    },
    db43_574:{
        archive:false,
        dataType:'R4',
        comment:'A液/B液比例',
    },
    db43_578:{
        archive:false,
        dataType:'R4',
        comment:'B液延迟开启时间',
    },
    db43_582:{
        archive:false,
        dataType:'R4',
        comment:'B液提前关闭时间',
    },
    db43_586:{
        archive:false,
        dataType:'R4',
        comment:'A液速度值',
    },
    I16_0:{
        archive:true,
        dataType:'B4',
        comment:'灯测试按钮',
    },
    I16_1:{
        archive:true,
        dataType:'B4',
        comment:'复位按钮',
    },
    I16_2:{
        archive:true,
        dataType:'B4',
        comment:'过滤泵启停',
    },
    I16_3:{
        archive:true,
        dataType:'B4',
        comment:'增压泵启停',
    },
    I16_4:{
        archive:true,
        dataType:'B4',
        comment:'内水泵启停',
    },
    I16_5:{
        archive:true,
        dataType:'B4',
        comment:'污水泵启停',
    },
    I17_0:{
        archive:true,
        dataType:'B4',
        comment:'齿轮油泵启停',
    },
    I17_1:{
        archive:true,
        dataType:'B4',
        comment:'EP2泵启停',
    },
    I17_2:{
        archive:true,
        dataType:'B4',
        comment:'HBW泵启停',
    },
    I17_3:{
        archive:true,
        dataType:'B4',
        comment:'刀盘主控室现场选择按钮',
    },
    I17_4:{
        archive:true,
        dataType:'B4',
        comment:'刀盘旋转停止按钮',
    },
    I17_5:{
        archive:true,
        dataType:'B4',
        comment:'刀盘旋转启动按钮',
    },
    I17_6:{
        archive:true,
        dataType:'B4',
        comment:'刀盘旋转高速按钮',
    },
    I17_7:{
        archive:true,
        dataType:'B4',
        comment:'刀盘旋转低速按钮',
    },
    I18_0:{
        archive:true,
        dataType:'B4',
        comment:'刀盘旋转左转按钮',
    },
    I18_1:{
        archive:true,
        dataType:'B4',
        comment:'刀盘旋转右转按钮',
    },
    I18_2:{
        archive:true,
        dataType:'B4',
        comment:'推进泵启停',
    },
    I18_3:{
        archive:true,
        dataType:'B4',
        comment:'控制泵启停',
    },
    I18_4:{
        archive:true,
        dataType:'B4',
        comment:'推进停止',
    },
    I18_5:{
        archive:true,
        dataType:'B4',
        comment:'推进模式启动按钮',
    },
    I18_6:{
        archive:true,
        dataType:'B4',
        comment:'管片模式启动按钮',
    },
    I18_7:{
        archive:true,
        dataType:'B4',
        comment:'铰接泵启动',
    },
    I19_0:{
        archive:true,
        dataType:'B4',
        comment:'管片安装机泵启停',
    },
    I19_1:{
        archive:true,
        dataType:'B4',
        comment:'铰接拖拉',
    },
    I19_2:{
        archive:true,
        dataType:'B4',
        comment:'铰接释放',
    },
    I19_3:{
        archive:true,
        dataType:'B4',
        comment:'盾尾密封油脂停止按钮',
    },
    I19_4:{
        archive:true,
        dataType:'B4',
        comment:'盾尾密封油脂启动按钮',
    },
    I19_5:{
        archive:true,
        dataType:'B4',
        comment:'盾尾密封油脂自动手动开关',
    },
    I19_6:{
        archive:true,
        dataType:'B4',
        comment:'辅助泵启停',
    },
    I19_7:{
        archive:true,
        dataType:'B4',
        comment:'超挖刀泵启停',
    },
    I20_0:{
        archive:true,
        dataType:'B4',
        comment:'螺旋输送机泵启停',
    },
    I20_1:{
        archive:true,
        dataType:'B4',
        comment:'螺旋机皮带机连锁开关',
    },
    I20_4:{
        archive:true,
        dataType:'B4',
        comment:'螺旋机主控室现场选择按钮',
    },
    I20_5:{
        archive:true,
        dataType:'B4',
        comment:'螺旋机高速按钮',
    },
    I20_6:{
        archive:true,
        dataType:'B4',
        comment:'螺旋机停止按钮',
    },
    I20_7:{
        archive:true,
        dataType:'B4',
        comment:'螺旋机正转按钮',
    },
    I21_0:{
        archive:true,
        dataType:'B4',
        comment:'螺旋机反转按钮',
    },
    I21_1:{
        archive:true,
        dataType:'B4',
        comment:'螺旋机上闸门开按钮',
    },
    I21_2:{
        archive:true,
        dataType:'B4',
        comment:'螺旋机上闸门关按钮',
    },
    I21_3:{
        archive:true,
        dataType:'B4',
        comment:'螺旋机下闸门开按钮',
    },
    I21_4:{
        archive:true,
        dataType:'B4',
        comment:'螺旋机下闸门关按钮',
    },
    I21_7:{
        archive:true,
        dataType:'B4',
        comment:'螺旋机前仓门开按钮',
    },
    I22_0:{
        archive:true,
        dataType:'B4',
        comment:'螺旋机前仓门关按钮',
    },
    I22_1:{
        archive:true,
        dataType:'B4',
        comment:'螺旋机伸出按钮',
    },
    I22_2:{
        archive:true,
        dataType:'B4',
        comment:'螺旋机回收按钮',
    },
    I22_3:{
        archive:true,
        dataType:'B4',
        comment:'螺旋机补油泵启停',
    },
    I22_4:{
        archive:true,
        dataType:'B4',
        comment:'膨润土泵停止按钮',
    },
    I22_5:{
        archive:true,
        dataType:'B4',
        comment:'膨润土泵启动按钮',
    },
    I22_6:{
        archive:true,
        dataType:'B4',
        comment:'盾壳膨润土泵停止按钮',
    },
    I22_7:{
        archive:true,
        dataType:'B4',
        comment:'盾壳膨润土泵启动按钮',
    },
    I23_0:{
        archive:true,
        dataType:'B4',
        comment:'膨润土1路启停按钮',
    },
    I23_1:{
        archive:true,
        dataType:'B4',
        comment:'膨润土2路启停按钮',
    },
    I23_2:{
        archive:true,
        dataType:'B4',
        comment:'注浆泵启停',
    },
    I23_3:{
        archive:true,
        dataType:'B4',
        comment:'泡沫停止按钮',
    },
    I23_4:{
        archive:true,
        dataType:'B4',
        comment:'泡沫手动按钮',
    },
    I23_5:{
        archive:true,
        dataType:'B4',
        comment:'泡沫半自动按钮',
    },
    I23_6:{
        archive:true,
        dataType:'B4',
        comment:'泡沫自动按钮',
    },
    I24_0:{
        archive:true,
        dataType:'B4',
        comment:'皮带机停止按钮',
    },
    I24_1:{
        archive:true,
        dataType:'B4',
        comment:'皮带机启动按钮',
    },
    I24_4:{
        archive:true,
        dataType:'B4',
        comment:'皮带机主控室现场控制按钮',
    },
    I25_0:{
        archive:true,
        dataType:'B4',
        comment:'二次风机启停',
    },
    I25_1:{
        archive:true,
        dataType:'B4',
        comment:'空压机1启停（电驱）',
    },
    I25_2:{
        archive:true,
        dataType:'B4',
        comment:'空压机2启停（电驱）',
    },
    I25_4:{
        archive:true,
        dataType:'B4',
        comment:'刀盘补油泵启停',
    },
    I25_5:{
        archive:true,
        dataType:'B4',
        comment:'主驱动1启停',
    },
    I25_6:{
        archive:true,
        dataType:'B4',
        comment:'主驱动2启停',
    },
    I25_7:{
        archive:true,
        dataType:'B4',
        comment:'主驱动3启停',
    },
    I141_0:{
        archive:true,
        dataType:'B4',
        comment:'人仓刀盘驱动紧急停止/维保开关按钮',
    },
    I141_1:{
        archive:true,
        dataType:'B4',
        comment:'人仓刀盘现场主控室切换按钮',
    },
    I141_2:{
        archive:true,
        dataType:'B4',
        comment:'人仓刀盘逆转按钮',
    },
    I141_3:{
        archive:true,
        dataType:'B4',
        comment:'人仓刀盘顺转按钮',
    },
    M11_2:{
        archive:true,
        dataType:'B4',
        comment:'新的一环开始',
    },
    M11_3:{
        archive:true,
        dataType:'B4',
        comment:'推进标志位',
    },
    M25_7:{
        archive:true,
        dataType:'B4',
        comment:'齿轮油泵运行',
    },
    M28_1:{
        archive:true,
        dataType:'B4',
        comment:'油脂填充使能',
    },
    M29_7:{
        archive:true,
        dataType:'B4',
        comment:'润滑油脂泵运行',
    },
    M50_3:{
        archive:true,
        dataType:'B4',
        comment:'刀盘驱动主控制室控制',
    },
    M50_4:{
        archive:true,
        dataType:'B4',
        comment:'刀盘驱动就地控制',
    },
    M50_5:{
        archive:true,
        dataType:'B4',
        comment:'刀盘顺时针转',
    },
    M50_6:{
        archive:true,
        dataType:'B4',
        comment:'刀盘逆时针转',
    },
    M50_7:{
        archive:true,
        dataType:'B4',
        comment:'刀盘旋转低速',
    },
    M51_0:{
        archive:true,
        dataType:'B4',
        comment:'刀盘旋转高速',
    },
    M51_1:{
        archive:true,
        dataType:'B4',
        comment:'刀盘旋转启动',
    },
    M51_2:{
        archive:true,
        dataType:'B4',
        comment:'刀盘就地右转',
    },
    M51_3:{
        archive:true,
        dataType:'B4',
        comment:'刀盘就地左转',
    },
    M57_0:{
        archive:true,
        dataType:'B4',
        comment:'推进允许',
    },
    M58_3:{
        archive:true,
        dataType:'B4',
        comment:'管片安装模式',
    },
    M58_4:{
        archive:true,
        dataType:'B4',
        comment:'推进模式',
    },
    M58_6:{
        archive:true,
        dataType:'B4',
        comment:'推进油缸控制盒激活',
    },
    M60_0:{
        archive:true,
        dataType:'B4',
        comment:'盾尾密封自动模式',
    },
    M60_1:{
        archive:true,
        dataType:'B4',
        comment:'推进盾尾注脂自动模式',
    },
    M61_4:{
        archive:true,
        dataType:'B4',
        comment:'前后有注脂',
    },
    M61_6:{
        archive:true,
        dataType:'B4',
        comment:'推进模式盾尾密封正常',
    },
    M62_3:{
        archive:true,
        dataType:'B4',
        comment:'压力控制模式',
    },
    M71_2:{
        archive:true,
        dataType:'B4',
        comment:'行程控制模式',
    },
    M72_7:{
        archive:true,
        dataType:'B4',
        comment:'盾尾密封运行',
    },
    M74_1:{
        archive:true,
        dataType:'B4',
        comment:'盾体铰接右上控制',
    },
    M74_2:{
        archive:true,
        dataType:'B4',
        comment:'盾体铰接右下控制',
    },
    M74_3:{
        archive:true,
        dataType:'B4',
        comment:'盾体铰接左下控制',
    },
    M74_4:{
        archive:true,
        dataType:'B4',
        comment:'盾体铰接左上控制',
    },
    M82_0:{
        archive:true,
        dataType:'B4',
        comment:'空压机1 启动',
    },
    M82_4:{
        archive:true,
        dataType:'B4',
        comment:'空压机2 启动',
    },
    M113_0:{
        archive:true,
        dataType:'B4',
        comment:'注浆手动模式',
    },
    M113_2:{
        archive:true,
        dataType:'B4',
        comment:'注浆自动模式',
    },
    M113_4:{
        archive:true,
        dataType:'B4',
        comment:'注浆启动',
    },
    M113_6:{
        archive:true,
        dataType:'B4',
        comment:'自动注浆启动',
    },
    M114_0:{
        archive:true,
        dataType:'B4',
        comment:'A1注浆',
    },
    M114_1:{
        archive:true,
        dataType:'B4',
        comment:'A2注浆',
    },
    M114_2:{
        archive:true,
        dataType:'B4',
        comment:'A3注浆',
    },
    M114_3:{
        archive:true,
        dataType:'B4',
        comment:'A4注浆',
    },
    M115_0:{
        archive:true,
        dataType:'B4',
        comment:'一号电机激活（电驱）',
    },
    M115_2:{
        archive:true,
        dataType:'B4',
        comment:'二号电机激活（电驱）',
    },
    M115_4:{
        archive:true,
        dataType:'B4',
        comment:'三号电机激活（电驱）',
    },
    M115_6:{
        archive:true,
        dataType:'B4',
        comment:'四号电机激活（电驱）',
    },
    M116_0:{
        archive:true,
        dataType:'B4',
        comment:'手动注浆左上',
    },
    M116_1:{
        archive:true,
        dataType:'B4',
        comment:'手动注浆左下',
    },
    M116_2:{
        archive:true,
        dataType:'B4',
        comment:'手动注浆右下',
    },
    M116_3:{
        archive:true,
        dataType:'B4',
        comment:'手动注浆右上',
    },
    M118_3:{
        archive:true,
        dataType:'B4',
        comment:'搅拌启动',
    },
    M120_5:{
        archive:true,
        dataType:'B4',
        comment:'管片安装机爪头抓紧',
    },
    M121_4:{
        archive:true,
        dataType:'B4',
        comment:'管片安装机右转',
    },
    M121_5:{
        archive:true,
        dataType:'B4',
        comment:'管片安装机左转',
    },
    M122_3:{
        archive:true,
        dataType:'B4',
        comment:'膨润土泵启动',
    },
    M122_5:{
        archive:true,
        dataType:'B4',
        comment:'膨润土搅拌启动',
    },
    M123_3:{
        archive:true,
        dataType:'B4',
        comment:'盾壳膨润土运行',
    },
    M123_6:{
        archive:true,
        dataType:'B4',
        comment:'盾壳膨润土手动',
    },
    M123_7:{
        archive:true,
        dataType:'B4',
        comment:'盾壳膨润土自动',
    },
    M134_0:{
        archive:true,
        dataType:'B4',
        comment:'控制泵运行',
    },
    M134_1:{
        archive:true,
        dataType:'B4',
        comment:'刀盘补油泵运行',
    },
    M134_2:{
        archive:true,
        dataType:'B4',
        comment:'内循环水运行',
    },
    M134_3:{
        archive:true,
        dataType:'B4',
        comment:'主驱动软启动器运行1',
    },
    M134_4:{
        archive:true,
        dataType:'B4',
        comment:'主驱动软启动器运行2',
    },
    M134_5:{
        archive:true,
        dataType:'B4',
        comment:'推进泵运行',
    },
    M134_6:{
        archive:true,
        dataType:'B4',
        comment:'盾体紧急停止按钮正常',
    },
    M134_7:{
        archive:true,
        dataType:'B4',
        comment:'管片小车紧急停止按钮',
    },
    M135_0:{
        archive:true,
        dataType:'B4',
        comment:'注浆紧急停止按钮',
    },
    M135_1:{
        archive:true,
        dataType:'B4',
        comment:'螺机紧急停止未按下',
    },
    M135_2:{
        archive:true,
        dataType:'B4',
        comment:'螺旋输送机软启动器运行',
    },
    M135_3:{
        archive:true,
        dataType:'B4',
        comment:'辅助泵运行',
    },
    M135_4:{
        archive:true,
        dataType:'B4',
        comment:'皮带机运行',
    },
    M135_6:{
        archive:true,
        dataType:'B4',
        comment:'泡沫原液泵变频器运行',
    },
    M135_7:{
        archive:false,
        dataType:'B4',
        comment:'刀盘电机3运行',
    },
    M136_0:{
        archive:true,
        dataType:'B4',
        comment:'螺机补油泵运行',
    },
    M140_3:{
        archive:true,
        dataType:'B4',
        comment:'螺旋输送机启动',
    },
    M142_0:{
        archive:true,
        dataType:'B4',
        comment:'皮带机启动使能',
    },
    M142_1:{
        archive:true,
        dataType:'B4',
        comment:'皮带机主控制室控制',
    },
    M142_2:{
        archive:true,
        dataType:'B4',
        comment:'皮带机就地控制',
    },
    M143_0:{
        archive:true,
        dataType:'B4',
        comment:'皮带机主控制室启动',
    },
    M143_1:{
        archive:true,
        dataType:'B4',
        comment:'皮带机就地启动',
    },
    M146_3:{
        archive:true,
        dataType:'B4',
        comment:'螺旋输送机主控制室控制',
    },
    M146_4:{
        archive:true,
        dataType:'B4',
        comment:'螺旋输送机就地控制',
    },
    M146_5:{
        archive:true,
        dataType:'B4',
        comment:'螺旋输送机正转',
    },
    M146_6:{
        archive:true,
        dataType:'B4',
        comment:'螺旋输送机反转',
    },
    M147_1:{
        archive:true,
        dataType:'B4',
        comment:'螺旋输送机正反主控制室控制',
    },
    M147_2:{
        archive:true,
        dataType:'B4',
        comment:'螺旋输送机正转就地控制',
    },
    M147_3:{
        archive:true,
        dataType:'B4',
        comment:'螺旋输送机反转就地控制',
    },
    M148_4:{
        archive:true,
        dataType:'B4',
        comment:'螺旋输送机本地控制有效',
    },
    M148_5:{
        archive:true,
        dataType:'B4',
        comment:'螺旋输送机主控制室控制有效',
    },
    M148_7:{
        archive:true,
        dataType:'B4',
        comment:'高速运行',
    },
    M150_1:{
        archive:false,
        dataType:'B4',
        comment:'螺机补油泵压力正常',
    },
    M150_3:{
        archive:true,
        dataType:'B4',
        comment:'主驱动软启动器运行3',
    },
    M152_3:{
        archive:true,
        dataType:'B4',
        comment:'螺旋输送机后仓门开启正常',
    },
    M152_4:{
        archive:true,
        dataType:'B4',
        comment:'螺旋输送机土仓压力正常',
    },
    M192_1:{
        archive:true,
        dataType:'B4',
        comment:'压力控制模式',
    },
    M199_4:{
        archive:true,
        dataType:'B4',
        comment:'自动模式四路激活',
    },
    M199_5:{
        archive:true,
        dataType:'B4',
        comment:'管片安装机限位失效',
    },
    M199_7:{
        archive:true,
        dataType:'B4',
        comment:'泡沫有激活',
    },
    M200_7:{
        archive:true,
        dataType:'B4',
        comment:'HBW 外围允许启动',
    },
    M221_0:{
        archive:true,
        dataType:'B4',
        comment:'泡沫单元手动',
    },
    M221_1:{
        archive:true,
        dataType:'B4',
        comment:'泡沫单元半自动',
    },
    M221_2:{
        archive:true,
        dataType:'B4',
        comment:'泡沫单元自动',
    },
    M225_0:{
        archive:true,
        dataType:'B4',
        comment:'注浆上位机控制有效',
    },
    M225_1:{
        archive:true,
        dataType:'B4',
        comment:'注浆上位机控制自动模式',
    },
    M303_2:{
        archive:true,
        dataType:'B4',
        comment:'管片安装机左转逆转',
    },
    M303_3:{
        archive:true,
        dataType:'B4',
        comment:'管片安装机右转顺转',
    },
    M305_0:{
        archive:true,
        dataType:'B4',
        comment:'刀盘主控室控制',
    },
    M305_1:{
        archive:true,
        dataType:'B4',
        comment:'刀盘现场控制',
    },
    M318_0:{
        archive:true,
        dataType:'B4',
        comment:'五号电机激活（电驱）',
    },
    M318_2:{
        archive:true,
        dataType:'B4',
        comment:'六号电机激活（电驱）',
    },
    M330_1:{
        archive:true,
        dataType:'B4',
        comment:'本地搅拌机启动',
    },
    M330_3:{
        archive:true,
        dataType:'B4',
        comment:'本地搅拌机故障灯',
    },
    M330_6:{
        archive:true,
        dataType:'B4',
        comment:'主控室搅拌机启动',
    },
    M331_0:{
        archive:true,
        dataType:'B4',
        comment:'主控室搅拌机故障灯',
    },
    M400_0:{
        archive:true,
        dataType:'B4',
        comment:'聚合物1路 启动',
    },
    M400_2:{
        archive:true,
        dataType:'B4',
        comment:'聚合物2路 启动',
    },
    M400_5:{
        archive:true,
        dataType:'B4',
        comment:'聚合物罐搅拌启动',
    },
    M410_3:{
        archive:true,
        dataType:'B4',
        comment:'A/B液启动 允许',
    },
    M430_0:{
        archive:true,
        dataType:'B4',
        comment:'一号喷水手动',
    },
    M430_1:{
        archive:true,
        dataType:'B4',
        comment:'二号喷水手动',
    },
    M430_2:{
        archive:true,
        dataType:'B4',
        comment:'三号喷水手动',
    },
    M430_3:{
        archive:true,
        dataType:'B4',
        comment:'四号喷水手动',
    },
    M430_4:{
        archive:true,
        dataType:'B4',
        comment:'五号喷水手动',
    },
    M434_2:{
        archive:true,
        dataType:'B4',
        comment:'刀盘喷水自动',
    },
    M555_0:{
        archive:true,
        dataType:'B4',
        comment:'砂浆罐自动润滑启动',
    },
    M830_0:{
        archive:true,
        dataType:'B4',
        comment:'过滤泵手动控制',
    },
    M850_7:{
        archive:true,
        dataType:'B4',
        comment:'膨润土卷筒气动球阀动作',
    },
    M908_0:{
        archive:true,
        dataType:'B4',
        comment:'超挖刀伸出',
    },
    M909_0:{
        archive:true,
        dataType:'B4',
        comment:'超挖刀自动伸出',
    },
    M909_1:{
        archive:true,
        dataType:'B4',
        comment:'超挖刀手动伸出',
    },
    M909_2:{
        archive:true,
        dataType:'B4',
        comment:'超挖刀自动控制模式',
    },
    M910_0:{
        archive:true,
        dataType:'B4',
        comment:'超挖刀手动回缩',
    }
}