package com.base.code.generator;

import com.jfinal.plugin.activerecord.generator.ModelGenerator;
import com.jfinal.plugin.activerecord.generator.TableMeta;
/**
 * 
 * All rights Reserved, Designed By hxjd
 * @类名: JModelGenerator.java   
 * @包名: com.base.code.generator   
 * @描述: TODO(用一句话描述该文件做什么)   
 * @所属: 华夏九鼎     
 * @日期: 2018年1月29日 上午9:37:41   
 * @版本: V1.0 
 * @创建人：Administrator 
 * @修改人：Administrator
 * @版权: 2018 hxjd Inc. All rights reserved. 
 * @注意：本内容仅限于华夏九鼎内部传阅，禁止外泄以及用于其他的商业目的
 */
public class JModelGenerator extends ModelGenerator {

	public JModelGenerator(String modelPackageName,
			String baseModelPackageName, String modelOutputDir) {
		super(modelPackageName, baseModelPackageName, modelOutputDir);
		
		this.importTemplate = "import com.base.model.core.Table;%n"
				+ "import %s.%s;%n%n";
		
		this.classDefineTemplate =
				"/**%n" +
				" * Generated by JPress.%n" +
				" */%n" +
				"@Table(tableName=\"%s\",primaryKey=\"%s\")%n" +
				"public class %s extends %s<%s> {%n";
		
		
		this.daoTemplate = "\tprivate static final long serialVersionUID = 1L;%n%n";
		
	}
	
	@Override
	protected void genClassDefine(TableMeta tableMeta, StringBuilder ret) {
		ret.append(String.format(classDefineTemplate, tableMeta.name.split("_")[1],tableMeta.primaryKey,tableMeta.modelName, tableMeta.baseModelName, tableMeta.modelName));
	}

		
		

}
