package com.base.model.base;

import com.base.message.MessageKit;
import com.base.model.core.JModel;
import java.math.BigInteger;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.ehcache.CacheKit;
import com.jfinal.plugin.ehcache.IDataLoader;

/**
 *  Auto generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJCardrecord<M extends BaseJCardrecord<M>> extends JModel<M> implements IBean {

	public static final String CACHE_NAME = "cardrecord";
	public static final String METADATA_TYPE = "cardrecord";

	public static final String ACTION_ADD = "cardrecord:add";
	public static final String ACTION_DELETE = "cardrecord:delete";
	public static final String ACTION_UPDATE = "cardrecord:update";

	public void removeCache(Object key){
		if(key == null) {
			return;
		}
		CacheKit.remove(CACHE_NAME, key);
	}

	public void putCache(Object key,Object value){
		CacheKit.put(CACHE_NAME, key, value);
	}

	public M getCache(Object key){
		return CacheKit.get(CACHE_NAME, key);
	}

	public M getCache(Object key,IDataLoader dataloader){
		return CacheKit.get(CACHE_NAME, key, dataloader);
	}

	@Override
	public boolean equals(Object o) {
		if(o == null){ return false; }
		if(!(o instanceof BaseJCardrecord<?>)){return false;}

		BaseJCardrecord<?> m = (BaseJCardrecord<?>) o;
		if(m.getId() == null){return false;}

		return m.getId().compareTo(this.getId()) == 0;
	}

	@Override
	public boolean save() {
		boolean saved = super.save();
		if (saved) { MessageKit.sendMessage(ACTION_ADD, this); }
		return saved;
	}

	@Override
	public boolean delete() {
		boolean deleted = super.delete();
		if (deleted) { MessageKit.sendMessage(ACTION_DELETE, this); }
		return deleted;
	}

	@Override
	public boolean deleteById(Object idValue) {
		boolean deleted = super.deleteById(idValue);
		if (deleted) { MessageKit.sendMessage(ACTION_DELETE, this); }
		return deleted;
	}

	@Override
	public boolean update() {
		boolean update = super.update();
		if (update) { MessageKit.sendMessage(ACTION_UPDATE, this); }
		return update;
	}

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setEventTime(java.util.Date eventTime) {
		set("eventTime", eventTime);
	}

	public java.util.Date getEventTime() {
		return get("eventTime");
	}

	public void setEid(java.lang.Integer eid) {
		set("eid", eid);
	}

	public java.lang.Integer getEid() {
		return get("eid");
	}

	public void setEcode(java.lang.String ecode) {
		set("ecode", ecode);
	}

	public java.lang.String getEcode() {
		return get("ecode");
	}

	public void setEname(java.lang.String ename) {
		set("ename", ename);
	}

	public java.lang.String getEname() {
		return get("ename");
	}

	public void setCardno(java.lang.Integer cardno) {
		set("cardno", cardno);
	}

	public java.lang.Integer getCardno() {
		return get("cardno");
	}

	public void setDoorid(java.lang.Integer doorid) {
		set("doorid", doorid);
	}

	public java.lang.Integer getDoorid() {
		return get("doorid");
	}

	public void setDoorname(java.lang.String doorname) {
		set("doorname", doorname);
	}

	public java.lang.String getDoorname() {
		return get("doorname");
	}

	public void setEvent(java.lang.String event) {
		set("event", event);
	}

	public java.lang.String getEvent() {
		return get("event");
	}

}
