package com.base.model.base;

import com.base.message.MessageKit;
import com.base.model.core.JModel;
import java.math.BigInteger;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.ehcache.CacheKit;
import com.jfinal.plugin.ehcache.IDataLoader;

/**
 *  Auto generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJMediator<M extends BaseJMediator<M>> extends JModel<M> implements IBean {

	public static final String CACHE_NAME = "mediator";
	public static final String METADATA_TYPE = "mediator";

	public static final String ACTION_ADD = "mediator:add";
	public static final String ACTION_DELETE = "mediator:delete";
	public static final String ACTION_UPDATE = "mediator:update";

	public void removeCache(Object key){
		if(key == null) {
			return;
		}
		CacheKit.remove(CACHE_NAME, key);
	}

	public void putCache(Object key,Object value){
		CacheKit.put(CACHE_NAME, key, value);
	}

	public M getCache(Object key){
		return CacheKit.get(CACHE_NAME, key);
	}

	public M getCache(Object key,IDataLoader dataloader){
		return CacheKit.get(CACHE_NAME, key, dataloader);
	}

	@Override
	public boolean equals(Object o) {
		if(o == null){ return false; }
		if(!(o instanceof BaseJMediator<?>)){return false;}

		BaseJMediator<?> m = (BaseJMediator<?>) o;
		if(m.getId() == null){return false;}

		return m.getId().compareTo(this.getId()) == 0;
	}

	@Override
	public boolean save() {
		boolean saved = super.save();
		if (saved) { MessageKit.sendMessage(ACTION_ADD, this); }
		return saved;
	}

	@Override
	public boolean delete() {
		boolean deleted = super.delete();
		if (deleted) { MessageKit.sendMessage(ACTION_DELETE, this); }
		return deleted;
	}

	@Override
	public boolean deleteById(Object idValue) {
		boolean deleted = super.deleteById(idValue);
		if (deleted) { MessageKit.sendMessage(ACTION_DELETE, this); }
		return deleted;
	}

	@Override
	public boolean update() {
		boolean update = super.update();
		if (update) { MessageKit.sendMessage(ACTION_UPDATE, this); }
		return update;
	}

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setMediatorName(java.lang.String mediatorName) {
		set("mediator_name", mediatorName);
	}

	public java.lang.String getMediatorName() {
		return get("mediator_name");
	}

	public void setCamp(java.lang.String camp) {
		set("camp", camp);
	}

	public java.lang.String getCamp() {
		return get("camp");
	}

	public void setX(java.lang.String x) {
		set("x", x);
	}

	public java.lang.String getX() {
		return get("x");
	}

	public void setY(java.lang.String y) {
		set("y", y);
	}

	public java.lang.String getY() {
		return get("y");
	}

	public void setMediatorStauts(java.lang.String mediatorStauts) {
		set("mediator_stauts", mediatorStauts);
	}

	public java.lang.String getMediatorStauts() {
		return get("mediator_stauts");
	}

	public void setMediatorGrade(java.lang.String mediatorGrade) {
		set("mediator_grade", mediatorGrade);
	}

	public java.lang.String getMediatorGrade() {
		return get("mediator_grade");
	}

	public void setDrillId(java.lang.Integer drillId) {
		set("drillId", drillId);
	}

	public java.lang.Integer getDrillId() {
		return get("drillId");
	}

}
