package com.base.model.base;

import com.base.message.MessageKit;
import com.base.model.core.JModel;
import java.math.BigInteger;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.ehcache.CacheKit;
import com.jfinal.plugin.ehcache.IDataLoader;

/**
 *  Auto generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJTbm<M extends BaseJTbm<M>> extends JModel<M> implements IBean {

	public static final String CACHE_NAME = "tbm";
	public static final String METADATA_TYPE = "tbm";

	public static final String ACTION_ADD = "tbm:add";
	public static final String ACTION_DELETE = "tbm:delete";
	public static final String ACTION_UPDATE = "tbm:update";

	public void removeCache(Object key){
		if(null == key) {
			return;
		}
		CacheKit.remove(CACHE_NAME, key);
	}

	public void putCache(Object key,Object value){
		CacheKit.put(CACHE_NAME, key, value);
	}

	public M getCache(Object key){
		return CacheKit.get(CACHE_NAME, key);
	}

	public M getCache(Object key,IDataLoader dataloader){
		return CacheKit.get(CACHE_NAME, key, dataloader);
	}

	@Override
	public boolean equals(Object o) {
		if(o == null){ return false; }
		if(!(o instanceof BaseJTbm<?>)){return false;}

		BaseJTbm<?> m = (BaseJTbm<?>) o;
		if(m.getId() == null){return false;}

		return m.getId().compareTo(this.getId()) == 0;
	}

	@Override
	public boolean save() {
		boolean saved = super.save();
		if (saved) { MessageKit.sendMessage(ACTION_ADD, this); }
		return saved;
	}

	@Override
	public boolean delete() {
		boolean deleted = super.delete();
		if (deleted) { MessageKit.sendMessage(ACTION_DELETE, this); }
		return deleted;
	}

	@Override
	public boolean deleteById(Object idValue) {
		boolean deleted = super.deleteById(idValue);
		if (deleted) { MessageKit.sendMessage(ACTION_DELETE, this); }
		return deleted;
	}

	@Override
	public boolean update() {
		boolean update = super.update();
		if (update) { MessageKit.sendMessage(ACTION_UPDATE, this); }
		return update;
	}

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}

	public java.lang.String getCode() {
		return get("code");
	}

	public void setWorksiteid(java.lang.Integer worksiteid) {
		set("worksiteid", worksiteid);
	}

	public java.lang.Integer getWorksiteid() {
		return get("worksiteid");
	}

	public void setMac(java.lang.String mac) {
		set("mac", mac);
	}

	public java.lang.String getMac() {
		return get("mac");
	}

	public void setCoord(java.lang.String coord) {
		set("coord", coord);
	}

	public java.lang.String getCoord() {
		return get("coord");
	}

}
