package com.base.model.base;

import com.base.message.MessageKit;
import com.base.model.core.JModel;
import java.math.BigInteger;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.ehcache.CacheKit;
import com.jfinal.plugin.ehcache.IDataLoader;

/**
 *  Auto generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJGrademark<M extends BaseJGrademark<M>> extends JModel<M> implements IBean {

	public static final String CACHE_NAME = "grademark";
	public static final String METADATA_TYPE = "grademark";

	public static final String ACTION_ADD = "grademark:add";
	public static final String ACTION_DELETE = "grademark:delete";
	public static final String ACTION_UPDATE = "grademark:update";

	public void removeCache(Object key){
		if(key == null) {
			return;
		}
		CacheKit.remove(CACHE_NAME, key);
	}

	public void putCache(Object key,Object value){
		CacheKit.put(CACHE_NAME, key, value);
	}

	public M getCache(Object key){
		return CacheKit.get(CACHE_NAME, key);
	}

	public M getCache(Object key,IDataLoader dataloader){
		return CacheKit.get(CACHE_NAME, key, dataloader);
	}

	@Override
	public boolean equals(Object o) {
		if(o == null){ return false; }
		if(!(o instanceof BaseJGrademark<?>)){return false;}

		BaseJGrademark<?> m = (BaseJGrademark<?>) o;
		if(m.getId() == null){return false;}

		return m.getId().compareTo(this.getId()) == 0;
	}

	@Override
	public boolean save() {
		boolean saved = super.save();
		if (saved) { MessageKit.sendMessage(ACTION_ADD, this); }
		return saved;
	}

	@Override
	public boolean delete() {
		boolean deleted = super.delete();
		if (deleted) { MessageKit.sendMessage(ACTION_DELETE, this); }
		return deleted;
	}

	@Override
	public boolean deleteById(Object idValue) {
		boolean deleted = super.deleteById(idValue);
		if (deleted) { MessageKit.sendMessage(ACTION_DELETE, this); }
		return deleted;
	}

	@Override
	public boolean update() {
		boolean update = super.update();
		if (update) { MessageKit.sendMessage(ACTION_UPDATE, this); }
		return update;
	}

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setGradeParentId(java.lang.Integer gradeParentId) {
		set("gradeParentId", gradeParentId);
	}

	public java.lang.Integer getGradeParentId() {
		return get("gradeParentId");
	}

	public void setNameParentId(java.lang.Integer nameParentId) {
		set("nameParentId", nameParentId);
	}

	public java.lang.Integer getNameParentId() {
		return get("nameParentId");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setScore(java.lang.String score) {
		set("score", score);
	}

	public java.lang.String getScore() {
		return get("score");
	}

	public void setMark(java.lang.String mark) {
		set("mark", mark);
	}

	public java.lang.String getMark() {
		return get("mark");
	}

	public void setTotal(java.lang.String total) {
		set("total", total);
	}

	public java.lang.String getTotal() {
		return get("total");
	}

	public void setCamp(java.lang.String camp) {
		set("camp", camp);
	}

	public java.lang.String getCamp() {
		return get("camp");
	}

	public void setDrillname(java.lang.String drillname) {
		set("drillname", drillname);
	}

	public java.lang.String getDrillname() {
		return get("drillname");
	}

}
