package com.base.model.base;

import com.base.message.MessageKit;
import com.base.model.core.JModel;
import java.math.BigInteger;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.ehcache.CacheKit;
import com.jfinal.plugin.ehcache.IDataLoader;

/**
 *  Auto generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJRecinstruction<M extends BaseJRecinstruction<M>> extends JModel<M> implements IBean {

	public static final String CACHE_NAME = "recinstruction";
	public static final String METADATA_TYPE = "recinstruction";

	public static final String ACTION_ADD = "recinstruction:add";
	public static final String ACTION_DELETE = "recinstruction:delete";
	public static final String ACTION_UPDATE = "recinstruction:update";

	public void removeCache(Object key){
		if(key == null) {
			return;
		}
		CacheKit.remove(CACHE_NAME, key);
	}

	public void putCache(Object key,Object value){
		CacheKit.put(CACHE_NAME, key, value);
	}

	public M getCache(Object key){
		return CacheKit.get(CACHE_NAME, key);
	}

	public M getCache(Object key,IDataLoader dataloader){
		return CacheKit.get(CACHE_NAME, key, dataloader);
	}

	@Override
	public boolean equals(Object o) {
		if(o == null){ return false; }
		if(!(o instanceof BaseJRecinstruction<?>)){return false;}

		BaseJRecinstruction<?> m = (BaseJRecinstruction<?>) o;
		if(m.getId() == null){return false;}

		return m.getId().compareTo(this.getId()) == 0;
	}

	@Override
	public boolean save() {
		boolean saved = super.save();
		if (saved) { MessageKit.sendMessage(ACTION_ADD, this); }
		return saved;
	}

	@Override
	public boolean delete() {
		boolean deleted = super.delete();
		if (deleted) { MessageKit.sendMessage(ACTION_DELETE, this); }
		return deleted;
	}

	@Override
	public boolean deleteById(Object idValue) {
		boolean deleted = super.deleteById(idValue);
		if (deleted) { MessageKit.sendMessage(ACTION_DELETE, this); }
		return deleted;
	}

	@Override
	public boolean update() {
		boolean update = super.update();
		if (update) { MessageKit.sendMessage(ACTION_UPDATE, this); }
		return update;
	}

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setMediatorId(java.lang.Integer mediatorId) {
		set("mediatorId", mediatorId);
	}

	public java.lang.Integer getMediatorId() {
		return get("mediatorId");
	}

	public void setMediatorName(java.lang.String mediatorName) {
		set("mediatorName", mediatorName);
	}

	public java.lang.String getMediatorName() {
		return get("mediatorName");
	}

	public void setMsgId(java.lang.String msgId) {
		set("msgId", msgId);
	}

	public java.lang.String getMsgId() {
		return get("msgId");
	}

	public void setMsgRead(java.lang.String msgRead) {
		set("msgRead", msgRead);
	}

	public java.lang.String getMsgRead() {
		return get("msgRead");
	}

}
