package com.base.model.base;

import com.base.message.MessageKit;
import com.base.model.core.JModel;
import java.math.BigInteger;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.ehcache.CacheKit;
import com.jfinal.plugin.ehcache.IDataLoader;

/**
 *  Auto generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJPel<M extends BaseJPel<M>> extends JModel<M> implements IBean {

	public static final String CACHE_NAME = "pel";
	public static final String METADATA_TYPE = "pel";

	public static final String ACTION_ADD = "pel:add";
	public static final String ACTION_DELETE = "pel:delete";
	public static final String ACTION_UPDATE = "pel:update";

	public void removeCache(Object key){
		if(key == null) {
			return;
		}
		CacheKit.remove(CACHE_NAME, key);
	}

	public void putCache(Object key,Object value){
		CacheKit.put(CACHE_NAME, key, value);
	}

	public M getCache(Object key){
		return CacheKit.get(CACHE_NAME, key);
	}

	public M getCache(Object key,IDataLoader dataloader){
		return CacheKit.get(CACHE_NAME, key, dataloader);
	}

	@Override
	public boolean equals(Object o) {
		if(o == null){ return false; }
		if(!(o instanceof BaseJPel<?>)){return false;}

		BaseJPel<?> m = (BaseJPel<?>) o;
		if(m.getId() == null){return false;}

		return m.getId().compareTo(this.getId()) == 0;
	}

	@Override
	public boolean save() {
		boolean saved = super.save();
		if (saved) { MessageKit.sendMessage(ACTION_ADD, this); }
		return saved;
	}

	@Override
	public boolean delete() {
		boolean deleted = super.delete();
		if (deleted) { MessageKit.sendMessage(ACTION_DELETE, this); }
		return deleted;
	}

	@Override
	public boolean deleteById(Object idValue) {
		boolean deleted = super.deleteById(idValue);
		if (deleted) { MessageKit.sendMessage(ACTION_DELETE, this); }
		return deleted;
	}

	@Override
	public boolean update() {
		boolean update = super.update();
		if (update) { MessageKit.sendMessage(ACTION_UPDATE, this); }
		return update;
	}

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setOid(java.lang.String oid) {
		set("oid", oid);
	}

	public java.lang.String getOid() {
		return get("oid");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}

	public java.lang.String getCode() {
		return get("code");
	}

	public void setPelname(java.lang.String pelname) {
		set("pelname", pelname);
	}

	public java.lang.String getPelname() {
		return get("pelname");
	}

	public void setLocation(java.lang.String location) {
		set("location", location);
	}

	public java.lang.String getLocation() {
		return get("location");
	}

	public void setX(java.lang.String x) {
		set("x", x);
	}

	public java.lang.String getX() {
		return get("x");
	}

	public void setY(java.lang.String y) {
		set("y", y);
	}

	public java.lang.String getY() {
		return get("y");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}

	public java.lang.Integer getState() {
		return get("state");
	}

	public void setDamage(java.lang.Integer damage) {
		set("damage", damage);
	}

	public java.lang.Integer getDamage() {
		return get("damage");
	}

	public void setCamp(java.lang.String camp) {
		set("camp", camp);
	}

	public java.lang.String getCamp() {
		return get("camp");
	}

	public void setShape(java.lang.String shape) {
		set("shape", shape);
	}

	public java.lang.String getShape() {
		return get("shape");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setDrill(java.lang.Integer drill) {
		set("drill", drill);
	}

	public java.lang.Integer getDrill() {
		return get("drill");
	}

}
