package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJButton;

/**
 * Generated by JPress.
 */
@Table(tableName="button",primaryKey="id")
public class JButton extends BaseJButton<JButton> {
	private static final long serialVersionUID = 1L;

}
