package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJCamera;

/**
 * Generated by JPress.
 */
@Table(tableName="camera",primaryKey="id")
public class JCamera extends BaseJCamera<JCamera> {
	
}
