package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJCardrecord;

/**
 * Generated by JPress.
 */
@Table(tableName="cardrecord",primaryKey="id")
public class JCardrecord extends BaseJCardrecord<JCardrecord> {
	
}
