package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJCircuit;

/**
 * Generated by JPress.
 */
@Table(tableName="circuit",primaryKey="id")
public class JCircuit extends BaseJCircuit<JCircuit> {
	
}
