package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJDepartment;

/**
 * Generated by JPress.
 */
@Table(tableName="department",primaryKey="id")
public class JDepartment extends BaseJDepartment<JDepartment> {
    private static final long serialVersionUID = 1L;
    //部门类型
    public final static Integer TYPE_DEPARTMENT=1;
    //职称类型
    public final static Integer TYPE_POSITION=0;

}
