package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJDepartment;

/**
 * Generated by JPress.
 */
@Table(tableName="department",primaryKey="id")
public class JDepartment extends BaseJDepartment<JDepartment> {
	
}
