package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJDepartmentvisitor;

/**
 * Generated by JPress.
 */
@Table(tableName="departmentvisitor",primaryKey="id")
public class JDepartmentvisitor extends BaseJDepartmentvisitor<JDepartmentvisitor> {
	
}
