package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJDepartmentuser;

/**
 * Generated by JPress.
 */
@Table(tableName="departmentuser",primaryKey="id")
public class JDepartmentuser extends BaseJDepartmentuser<JDepartmentuser> {
	
}
