package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJDrillcode;

/**
 * Generated by JPress.
 */
@Table(tableName="drillcode",primaryKey="id")
public class JDrillcode extends BaseJDrillcode<JDrillcode> {
	
}
