package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJGrademark;

/**
 * Generated by JPress.
 */
@Table(tableName="grademark",primaryKey="id")
public class JGrademark extends BaseJGrademark<JGrademark> {
	
}
