package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJGroupmediator;

/**
 * Generated by JPress.
 */
@Table(tableName="groupmediator",primaryKey="id")
public class JGroupmediator extends BaseJGroupmediator<JGroupmediator> {
	private static final long serialVersionUID = 1L;

}
