package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJGroup;

/**
 * Generated by JPress.
 */
@Table(tableName="group",primaryKey="id")
public class JGroup extends BaseJGroup<JGroup> {
	private static final long serialVersionUID = 1L;

}
