package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJGroupdrill;

/**
 * Generated by JPress.
 */
@Table(tableName="groupdrill",primaryKey="id")
public class JGroupdrill extends BaseJGroupdrill<JGroupdrill> {
	
}
