package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJInstruction;

/**
 * Generated by JPress.
 */
@Table(tableName="instruction",primaryKey="id")
public class JInstruction extends BaseJInstruction<JInstruction> {
	
}
