package com.base.model;

import com.base.model.base.BaseJJob;
import com.base.model.core.Table;

/**
 * Generated by JPress.
 */
@Table(tableName="job",primaryKey="id")
public class JJob extends BaseJJob<JJob> {
	private static final long serialVersionUID = 1L;

}
