package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJKpi;

/**
 * Generated by JPress.
 */
@Table(tableName="kpi",primaryKey="id")
public class JKpi extends BaseJKpi<JKpi> {
	private static final long serialVersionUID = 1L;

}
