package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJKpiobject;

/**
 * Generated by JPress.
 */
@Table(tableName="kpiobject",primaryKey="id")
public class JKpiobject extends BaseJKpiobject<JKpiobject> {
	private static final long serialVersionUID = 1L;

}
