package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJMark;

/**
 * Generated by JPress.
 */
@Table(tableName="mark",primaryKey="id")
public class JMark extends BaseJMark<JMark> {
	private static final long serialVersionUID = 1L;

}
