package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJMedseat;

/**
 * Generated by JPress.
 */
@Table(tableName="medseat",primaryKey="id")
public class JMedseat extends BaseJMedseat<JMedseat> {
	private static final long serialVersionUID = 1L;

}
