package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJMediatorterminal;

/**
 * Generated by JPress.
 */
@Table(tableName="mediatorterminal",primaryKey="id")
public class JMediatorterminal extends BaseJMediatorterminal<JMediatorterminal> {
	private static final long serialVersionUID = 1L;

}
