package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJMediator;

/**
 * Generated by JPress.
 */
@Table(tableName="mediator",primaryKey="id")
public class JMediator extends BaseJMediator<JMediator> {
	private static final long serialVersionUID = 1L;

}
