package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJMediatordrill;

/**
 * Generated by JPress.
 */
@Table(tableName="mediatordrill",primaryKey="id")
public class JMediatordrill extends BaseJMediatordrill<JMediatordrill> {
	
}
