package com.base.model;

import com.base.model.base.BaseJMenu;
import com.base.model.core.Table;

/**
 * Generated by JPress.
 */
@Table(tableName="menu",primaryKey="id")
public class JMenu extends BaseJMenu<JMenu> {
	private static final long serialVersionUID = 1L;
	
	
}
