package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJMessageall;

/**
 * Generated by JPress.
 */
@Table(tableName="messageall",primaryKey="id")
public class JMessageall extends BaseJMessageall<JMessageall> {
	
}
