package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJMsg;

/**
 * Generated by JPress.
 */
@Table(tableName="msg",primaryKey="id")
public class JMsg extends BaseJMsg<JMsg> {
	private static final long serialVersionUID = 1L;

}
