package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJNewstype;

/**
 * Generated by JPress.
 */
@Table(tableName="newstype",primaryKey="id")
public class JNewstype extends BaseJNewstype<JNewstype> {
	
}
