package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJNews;

/**
 * Generated by JPress.
 */
@Table(tableName="news",primaryKey="id")
public class JNews extends BaseJNews<JNews> {
	
}
