package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJObjectmed;

/**
 * Generated by JPress.
 */
@Table(tableName="objectmed",primaryKey="id")
public class JObjectmed extends BaseJObjectmed<JObjectmed> {
	private static final long serialVersionUID = 1L;

}
