package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJObject;

/**
 * Generated by JPress.
 */
@Table(tableName="object",primaryKey="id")
public class JObject extends BaseJObject<JObject> {
	private static final long serialVersionUID = 1L;

}
