package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJOffuser;

/**
 * Generated by JPress.
 */
@Table(tableName="offuser",primaryKey="id")
public class JOffuser extends BaseJOffuser<JOffuser> {
	private static final long serialVersionUID = 1L;

}
