package com.base.model;

import com.base.model.base.BaseJOption;
import com.base.model.core.Table;

/**
 * Generated by JPress.
 */
@Table(tableName="option",primaryKey="id")
public class JOption extends BaseJOption<JOption> {
	private static final long serialVersionUID = 1L;

}
