package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJPelgrouppel;

/**
 * Generated by JPress.
 */
@Table(tableName="pelgrouppel",primaryKey="id")
public class JPelgrouppel extends BaseJPelgrouppel<JPelgrouppel> {
	private static final long serialVersionUID = 1L;

}
