package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJPelgroup;

/**
 * Generated by JPress.
 */
@Table(tableName="pelgroup",primaryKey="id")
public class JPelgroup extends BaseJPelgroup<JPelgroup> {
	private static final long serialVersionUID = 1L;

}
