package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJPeldrill;

/**
 * Generated by JPress.
 */
@Table(tableName="peldrill",primaryKey="id")
public class JPeldrill extends BaseJPeldrill<JPeldrill> {
	
}
