package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJPelgroupdrill;

/**
 * Generated by JPress.
 */
@Table(tableName="pelgroupdrill",primaryKey="id")
public class JPelgroupdrill extends BaseJPelgroupdrill<JPelgroupdrill> {
	
}
