package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJPel;

/**
 * Generated by JPress.
 */
@Table(tableName="pel",primaryKey="id")
public class JPel extends BaseJPel<JPel> {
	private static final long serialVersionUID = 1L;

}
