package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJRecinstruction;

/**
 * Generated by JPress.
 */
@Table(tableName="recinstruction",primaryKey="id")
public class JRecinstruction extends BaseJRecinstruction<JRecinstruction> {
	
}
