package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJRolemenubutton;

/**
 * Generated by JPress.
 */
@Table(tableName="rolemenubutton",primaryKey="id")
public class JRolemenubutton extends BaseJRolemenubutton<JRolemenubutton> {
	private static final long serialVersionUID = 1L;

}
