package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJRole;

/**
 * Generated by JPress.
 */
@Table(tableName="role",primaryKey="id")
public class JRole extends BaseJRole<JRole> {
	private static final long serialVersionUID = 1L;

}
