package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJRoute;

/**
 * Generated by JPress.
 */
@Table(tableName="route",primaryKey="id")
public class JRoute extends BaseJRoute<JRoute> {
    //线路
	public static final int LINE_WAY = 0;
	//工点
	public static final int WORK_SITE = 1;
	//盾构机
	public static final int MACHINE = 2;

}
