package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJSeatpelgroup;

/**
 * Generated by JPress.
 */
@Table(tableName="seatpelgroup",primaryKey="id")
public class JSeatpelgroup extends BaseJSeatpelgroup<JSeatpelgroup> {
	private static final long serialVersionUID = 1L;

}
