package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJSeatdrill;

/**
 * Generated by JPress.
 */
@Table(tableName="seatdrill",primaryKey="id")
public class JSeatdrill extends BaseJSeatdrill<JSeatdrill> {
	
}
