package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJSeat;

/**
 * Generated by JPress.
 */
@Table(tableName="seat",primaryKey="id")
public class JSeat extends BaseJSeat<JSeat> {
	private static final long serialVersionUID = 1L;

}
