package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJTag;

/**
 * Generated by JPress.
 */
@Table(tableName="tag",primaryKey="id")
public class JTag extends BaseJTag<JTag> {
	
}
