package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJTbm;

/**
 * Generated by JPress.
 */
@Table(tableName="tbm",primaryKey="id")
public class JTbm extends BaseJTbm<JTbm> {
	
}
