package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJTbmrepair;

/**
 * Generated by JPress.
 * 盾构机维修记录
 */
@Table(tableName="tbmrepair",primaryKey="id")
public class JTbmrepair extends BaseJTbmrepair<JTbmrepair> {
	
}
