package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJTemplate;

/**
 * Generated by JPress.
 */
@Table(tableName="template",primaryKey="id")
public class JTemplate extends BaseJTemplate<JTemplate> {
	
}
