package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJTerminal;

/**
 * Generated by JPress.
 */
@Table(tableName="terminal",primaryKey="id")
public class JTerminal extends BaseJTerminal<JTerminal> {
	private static final long serialVersionUID = 1L;

}
