package com.base.model;

import com.base.model.base.BaseJUser;
import com.base.model.core.Table;

/**
 * Generated by JPress.
 */
@Table(tableName="user",primaryKey="id")
public class JUser extends BaseJUser<JUser> {
	private static final long serialVersionUID = 1L;

}
