package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJUserrole;

/**
 * Generated by JPress.
 */
@Table(tableName="userrole",primaryKey="id")
public class JUserrole extends BaseJUserrole<JUserrole> {
	private static final long serialVersionUID = 1L;

}
