package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJUsergrade;

/**
 * Generated by JPress.
 */
@Table(tableName="usergrade",primaryKey="id")
public class JUsergrade extends BaseJUsergrade<JUsergrade> {
	
}
