package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJVisitor;

/**
 * Generated by JPress.
 *只有访问权限的用户
 */
@Table(tableName="visitor",primaryKey="id")
public class JVisitor extends BaseJVisitor<JVisitor> {
    private static final long serialVersionUID = 1L;
}
