package com.base.model;

import com.base.model.core.Table;
import com.base.model.base.BaseJWorksite;

/**
 * Generated by JPress.
 */
@Table(tableName="worksite",primaryKey="id")
public class JWorksite extends BaseJWorksite<JWorksite> {
	
}
